### ISSUE TITLE
pcap file support

### ISSUE THREAD

**Issue by JaimeGomezGarciaSan** [Santandersecurityresearch/CryptoMon#11]
Sometimes it is difficult to capture network traffic were you can deploy CryptoMon.
I would like Cryptomon to support pcap files to help me bring packet captures taken elsewhere.

**Comment by JaimeGomezGarciaSan** [comment]
Great! I suggest that this info is included in the Readme.md and this issue closed.

**Comment by unprovable** [comment]
PR #16 should fix this. Closing for now but we should keep an eye on better ways to parse PCAPs in the future. :)
